application:
  guide:
    -
      name: EUR/USD
      basic: EUR
      quote: USD
      basicCountry: Europe
      quoteCountry: USA
      isMajor: true
    -
      name: USD/RUB
      basic: USD
      quote: RUB
      basicCountry: USA
      quoteCountry: Russia
      isMajor: false




server:
  error:
    include-message: always
    include-stacktrace: never
  port: 8080

spring:
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:src/main/resources/db./db # по пути будут созданы два файла: бд db.mv.db, db.trace.db
    # Вход в базу данных jdbc:h2:file:src/main/resources/db./db
    username: user_db # имя пользователя консоли
    password: 123_db # пароль консоли

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true

  h2:
    console:
      enabled: true